4.x
Story-Chief/joomla-component-storychief pull request #2
Opened 2022-07-20 10:18 UTC by bastiaandewaele

## Description

This PR upgrades our code to be compatible with Joomla 4. 

- Made the code compatible with Joomla 4
- Added support for creating categories (new feature)
- Changed the license to GPL-3
- Changed the readme
  -  FAQ: custom fields requires the permissions to be changed to public

Because of a lot of code got refactored, our plugin no longer supports Joomla 3. Supporting both versions would have added to much complexity. 

To keep supporting both version I have added these branches.

- [3.X](https://github.com/Story-Chief/joomla-component-storychief/tree/3.x) -> Joomla 3
- [4.X](https://github.com/Story-Chief/joomla-component-storychief/tree/4.x) -> Joomla 4
- [develop](https://github.com/Story-Chief/joomla-component-storychief/tree/develop) -> Joomla 4

Once this PR is approved and merged, the master branch will also become **Joomla 4**. But we will still have our branch [3.X](https://github.com/Story-Chief/joomla-component-storychief/tree/3.x) to pushing bug-fixes to Joomla 3.

## Testing notes

Download the source code and install it in a Joomla 4 environment. 

- Connect channel in StoryChief
- Publish
- Update
- Unpublish
- ... 

## Release notes

The Joomla destination detail / edit page contains a link to (button "view plugin"):

https://github.com/Story-Chief/joomla-component-storychief/tree/v1.0.13

This needs to be changed to:

https://github.com/Story-Chief/joomla-component-storychief/releases

2022-07-20 11:57 UTC, gregory-claeyssens commented on README.md
>  2. Add a 'Custom Website' channel
Think this is outdated

2022-07-20 11:59 UTC, gregory-claeyssens commented
Issue when installing (screenshot). It does install the component properly though so it's just a warning
![Screenshot 2022-07-20 135008](https://user-images.githubusercontent.com/5057847/179976485-24bf0168-7430-41be-9f9c-7b9943c6c603.jpg)

2022-07-20 11:59 UTC, gregory-claeyssens commented
I suggest renaming the 'field mapping' to 'custom field mapping'
![Screenshot 2022-07-20 135018](https://user-images.githubusercontent.com/5057847/179976576-4af9b013-3e98-4597-90ad-85f6cc8af3c2.jpg)

2022-07-20 12:01 UTC, gregory-claeyssens commented
Notices when publishing (Postman collection>publish event)
![image](https://user-images.githubusercontent.com/5057847/179976923-3d9cc0bb-3563-47ed-a07b-df06bc649e03.png)
![image](https://user-images.githubusercontent.com/5057847/179976949-9f41b2d1-907c-48a1-bdc1-35aaa5e2def1.png)
![image](https://user-images.githubusercontent.com/5057847/179976980-ea69baec-fef9-44a4-9c50-535380f19453.png)

2022-07-20 16:08 UTC, gregory-claeyssens commented
FYI, in the end I'll delete master and develop branch and only keep the 3.x and 4.x branches.
Those branches will serve as the develop branch for each specific branch. Releases will be used for production ready plugin versions

2022-07-20 16:08 UTC, gregory-claeyssens requested changes

2022-07-20 16:08 UTC, gregory-claeyssens commented on README.md
>  2. Add a 'Custom Website' channel
This is outdated

2022-07-20 16:08 UTC, gregory-claeyssens commented on README.md
> +- Joomla! 4.0 or higher
Add instruction or reference to V3

2022-07-22 11:44 UTC, bastiaandewaele commented on README.md
>  2. Add a 'Custom Website' channel
See commit 1273483d23453698b66afe9ddcad1c1d6b8ff771

2022-07-22 11:47 UTC, bastiaandewaele commented
> I suggest renaming the 'field mapping' to 'custom field mapping' ![Screenshot 2022-07-20 135018](https://user-images.githubusercontent.com/5057847/179976576-4af9b013-3e98-4597-90ad-85f6cc8af3c2.jpg)

Please see commit e00d0cb717c3926a18f35686496107143b5d621e

2022-07-22 11:50 UTC, bastiaandewaele commented on README.md
> +- Joomla! 4.0 or higher
See commit 44e1b86730c5ef017daf2830456a90cc41e32951

2022-07-22 11:51 UTC, bastiaandewaele commented
> Issue when installing (screenshot). It does install the component properly though so it's just a warning ![Screenshot 2022-07-20 135008](https://user-images.githubusercontent.com/5057847/179976485-24bf0168-7430-41be-9f9c-7b9943c6c603.jpg)

See commit 65a594fb46e602dd0cff9aa7dadff9a594da6c4e

2022-07-22 12:59 UTC, bastiaandewaele commented
The PHP-errors should be fixed now for PHP 8.

2022-07-22 14:35 UTC, gregory-claeyssens approved these changes

2022-07-22 14:35 UTC, merged